### ISSUE TITLE
minidump.js commonds path error

### ISSUE THREAD

**Issue by weiweian90** [skelsec/minidump#18]
minidump version 0.19.0
I install minidump by   npm intall minidump@0.19.0 --no-bin-links
but node_modules/minidump/build have nothing,  the minidump.js content commands excute path minidump\build\src\processor\minidump_stackwalk.exe  is not exsit

**Comment by skelsec** [comment]
I believe you mixed up the repositories. This is not the `minidump.js` project, and I have no affiliation with the maintainers.
Please submit your issue here: https://github.com/electron/node-minidump
