### ISSUE TITLE
Bug: NameError: name 'MinidumpThreadExList' is not defined

### ISSUE THREAD

**Issue by pd-fkie** [skelsec/minidump#23]
In `minidump/minidumpfile.py` on [line 128](https://github.com/skelsec/minidump/blob/959b5380504a1983f59cbd97d246eefc4149fbc9/minidump/minidumpfile.py#L128) the method
`MinidumpThreadExList.parse` gets called but `MinidumpThreadExList` was not imported
resulting in the following exception:
```
NameError: name 'MinidumpThreadExList' is not defined
Traceback (most recent call last):
  File "fuzz_minidump.py", line 14, in test_one_input
    minidump.minidumpfile.MinidumpFile.parse_bytes(b"MDMP" + data)
  File "minidump/minidumpfile.py", line 66, in parse_bytes
    return MinidumpFile.parse_buff(io.BytesIO(data))
  File "minidump/minidumpfile.py", line 72, in parse_buff
    mf._parse()
  File "minidump/minidumpfile.py", line 80, in _parse
    self.__parse_directories()
  File "minidump/minidumpfile.py", line 128, in __parse_directories
    self.threads_ex = MinidumpThreadExList.parse(dir, self.file_handle)
```
The following minidump file can trigger the exception:    
[crash-237cd8dcdd1e26050f915932c17a9741c9600a4f](https://github.com/pd-fkie/crashes/raw/main/crash-237cd8dcdd1e26050f915932c17a9741c9600a4f)

**Comment by skelsec** [comment]
Hello, thank you for submitting this issue.
Yup, that's a problem I will fix it in the new release and get back to this issue to close it.

**Comment by skelsec** [comment]
Fixed in new release now.
