### ISSUE TITLE
About inrange()

### ISSUE THREAD

**Issue by JHGL0419** [skelsec/minidump#35]
In order to print the entire contents of the memory segment, I entered the segment size in the '-s' option, but it did not work.
So I looked at the inrange() code and found that "`start_address <= position < end_address`".
However, since end_address must also be included, isn't "`<= end_address correct`"?
![image](https://github.com/skelsec/minidump/assets/81086444/3c9f83c4-5a0d-4a15-a2cd-42c9eb0d049f)

**Comment by skelsec** [comment]
Every year this is a recurring topic. Last year it was a PR from @mrexodia which undid the previous year's change which was the way you're referring to.  
Please discuss it, and come to a conclusion :)

**Comment by mrexodia** [comment]
Let me read up on the code again, I’ve been reading the full memory region without issues after my change in Dumpulator: https://github.com/mrexodia/dumpulator/blob/main/src/dumpulator/dumpulator.py#L455

**Comment by mrexodia** [comment]
Could you give the full command line you used for this? I checked the code and everything looks like it should work 🤷🏻
